export let wrapper = document.querySelector('.wrapper');
export let header = document.querySelector('.header');
export let headerModal = document.querySelector('.headerModal');
export let header_form = document.querySelector('.header_form');
export let header_form_media = document.querySelector('.header_form_media');
export let input_search = document.querySelector('.input_search');
export let btn_search = document.querySelector('.btn_search');
export let submit_btn = document.querySelector('.buttons button[type="submit"]');
export let formSignUp = document.querySelector('#formSignUp');
export let product_buttons = document.querySelectorAll('.product_button');
export let clickField = document.querySelector('.clickField');
export let helper = document.querySelector('.helper');
export let sidebar_sale_game = document.querySelector('.sidebar_sale_game');
export let submitBtn = document.querySelector('#submit');
export let formAuth = document.querySelector('#formAuth');
